AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Book Store API

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  BookStoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.bookstore.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/bookstore-serverless-1.0-SNAPSHOT.jar
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  BookStoreApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/books'
    Export:
      Name: BookStoreApi
